baseURL = "https://hu-yating.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Ya Ting Hu"

enableEmoji = true
enableRobotsTXT = true
summaryLength = 0

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
tag = "tags"
category = "categories"

[services]
[services.googleAnalytics]
ID = "UA-122321624-2"
