colorScheme = "yat-navy"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = ["projects"]

[header]
layout = "fixed"

[footer]
showCopyright = true
showThemeAttribution = true

[homepage]
layout = "profile"
showRecent = false

[article]
showDate = true
showAuthor = false
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
showHeadingAnchors = true
showPagination = true
showReadingTime = false
showTableOfContents = true
showTaxonomies = true

[list]
showBreadcrumbs = true
showSummary = true
showTableOfContents = false

[sitemap]
excludedKinds = ["taxonomy", "term"]
